version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    env_file:
      - .env # Use the .env file for frontend service
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
    command: gunicorn --bind 0.0.0.0:5000 app:app
    ports:
      - '5000:5000'
    env_file:
      - .env # Use the .env file for backend service
    depends_on:
      - db
  db:
    image: postgres:latest
    env_file:
      - .env # Use the .env file for db service
    environment:
      POSTGRES_DB: mlguess
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    depends_on:
      - frontend
