services:
  - type: web
    name: frontend
    runtime: docker
    dockerfile: frontend/Dockerfile
    ports:
      - 3000

  - type: web
    name: backend
    dockerfile: backend/Dockerfile
    ports:
      - 5000
    envVars:
      - key: POSTGRES_DB
        value: POSTGRES_DB
      - key: POSTGRES_USER
        value: POSTGRES_USER
      - key: POSTGRES_PASSWORD
        value: POSTGRES_PASSWORD
    dependencies:
      - name: db
        ports:
          - 5432

databases:
  - name: db
