databases:
  - name: db
    databaseName: mlguess
    postgresMajorVersion: 14
    
services:
  - type: web
    name: frontend
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile

  - type: web
    name: backend
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: POSTGRES_DB
        value: POSTGRES_DB
      - key: POSTGRES_USER
        value: POSTGRES_USER
      - key: POSTGRES_PASSWORD
        value: POSTGRES_PASSWORD

