databases:
  - name: db
    databaseName: mlguess
    postgresMajorVersion: 14
    
services:
  - type: web
    name: frontend
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile

  - type: web
    name: backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile

